// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnrbzmgmpczyuupmfjmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InducmJ6bWdtcGN6eXV1cG1mam1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTc3OTIsImV4cCI6MjA2NTE5Mzc5Mn0.ND2nLpzyblDtDjCW3WXfFNT_77ClfYp0aOxSB5puJZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);