// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxikpxczmuchjacumzhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4aWtweGN6bXVjaGphY3VtemhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTAxODQsImV4cCI6MjA2MzU2NjE4NH0._uP1Zw5WRxH601XYDJkCzBiHbGImn0pN-2VOtv0ldNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);